.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PROJECT\-INIT" "1" "September 2015" "" "Git Project"
.
.SH "NAME"
\fBgit\-project\-init\fR \- Create Git Project
.
.SH "SYNOPSIS"
\fBgit\-project\-init\fR [\-h,\-\-help] [\-o,\-\-origin] [\-p,\-\-print\-template] [\-t,\-\-template=<template>] [<directory>]
.
.SH "DESCRIPTION"
Creates an empty git project repository from the template specified in project configuration\. If directory is left out, current directory is used\.
.
.SH "OPTIONS"
.
.TP
\-o,\-\-origin
Specify a remote orgin repository to be setup at start
.
.TP
\-\-print\-template
Print the current configured template and exit
.
.TP
\-t, \-\-template=<template>
Use the repository path specified instead of project configuration
.
.P
The repository used by default is configured in git\'s configuration: \fBgit config project\.template\fR
.
.P
It is located in the system configuration by default, global configuration in case of user\-installation\.
.
.SH "DETAILS"
git\-project\-init performs:
.
.IP "\(bu" 4
git clone TEMPLATE \.
.
.IP "\(bu" 4
git submodule init
.
.IP "\(bu" 4
git remote remove origin
.
.IP "\(bu" 4
git submodule update \-\-init \-\-recursive
.
.IP "\(bu" 4
git remote add origin ORIGIN
.
.IP "" 0
.
.SH "COPYRIGHT"
\(co DevConSoft, 2015
.
.P
\(co Zenterio AB, 2015
.
.SH "LICENCE"
\fBgit\-project\fR is released under the MIT License \fIhttp://opensource\.org/licenses/mit\-license\.html\fR\.
.
.SH "REPORTING BUGS"
TBD
.
.SH "SEE ALSO"
TBD
