.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PROJECT\-CLONE" "1" "September 2015" "" "Git Project"
.
.SH "NAME"
\fBgit\-project\-clone\fR \- Clone a project repository
.
.SH "SYNOPSIS"
\fBgit\-project\-clone\fR [\-h,\-\-help] [<OPTIONS>]
.
.SH "DESCRIPTION"
Clones the project repository and performs needed initialization\.
.
.SH "OPTIONS"
.
.TP
\-h
Print short usage description and exit
.
.TP
\-\-help
Show this man page and exit
.
.P
git\-project\-clone supports the same options as \fIgit clone\fR\.
.
.SH "DETAILS"
git\-project\-clone performs:
.
.IP "\(bu" 4
git clone \-\-recursive\-submodules REPO [DIR]
.
.IP "" 0
.
.SH "COPYRIGHT"
\(co DevConSoft, 2015
.
.P
\(co Zenterio AB, 2015
.
.SH "LICENCE"
\fBgit\-project\fR is released under the MIT License \fIhttp://opensource\.org/licenses/mit\-license\.html\fR\.
.
.SH "REPORTING BUGS"
TBD
.
.SH "SEE ALSO"
TBD
