.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PROJECT\-MANUAL" "1" "September 2015" "" "Git Project"
.
.SH "NAME"
\fBgit\-project\-manual\fR \- git project manual
.
.SH "SYNOPSIS"
\fBgit\-project\-manual\fR [\-h,\-\-help]
.
.SH "DESCRIPTION"
Shows the git\-project manual\. Same as \fBgit help gitproject\-userguide\fR\.
.
.SH "OPTIONS"
.
.TP
\-h
Print usage\.
.
.TP
\-\-help
Show this help\.
.
.TP
git help options
The manual command is a wrapper for \fBgit help gitproject\-userguide\fR and any additional options will be passed to that command\.
.
.SH "COPYRIGHT"
\(co DevConSoft, 2015
.
.P
\(co Zenterio AB, 2015
.
.SH "LICENCE"
\fBgit\-project\fR is released under the MIT License \fIhttp://opensource\.org/licenses/mit\-license\.html\fR\.
.
.SH "REPORTING BUGS"
TBD
.
.SH "SEE ALSO"
TBD
