.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-PROJECT\-STATUS" "1" "September 2015" "" "Git Project"
.
.SH "NAME"
\fBgit\-project\-status\fR \- Show project status
.
.SH "SYNOPSIS"
\fBgit\-project\-status\fR [\-h,\-\-help]
.
.SH "DESCRIPTION"
Prints the status of the project and its components\.
.
.SH "OPTIONS"
.
.TP
\-h
Print short usage description and exit
.
.TP
\-\-help
Show this man page and exit
.
.SH "DETAILS"
git\-project\-status performs:
.
.P
from the top project directory:
.
.IP "\(bu" 4
git status
.
.IP "\(bu" 4
git submodule foreach \'git status\'
.
.IP "" 0
.
.SH "COPYRIGHT"
\(co DevConSoft, 2015
.
.P
\(co Zenterio AB, 2015
.
.SH "LICENCE"
\fBgit\-project\fR is released under the MIT License \fIhttp://opensource\.org/licenses/mit\-license\.html\fR\.
.
.SH "REPORTING BUGS"
TBD
.
.SH "SEE ALSO"
TBD
