.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GITPROJECT\-ROADMAP" "7" "September 2015" "" "Git Project"
.
.SH "NAME"
\fBgitproject\-roadmap\fR \- Roadmap for git\-project
.
.SH "INTRODUCTION"
This page contains information about the unofficial road\-map for git\-project\. Stuff yet not implemented\.
.
.SH "HIGH PRIO"
.
.IP "1." 4

.
.IP "" 0
.
.SH "COMMANDS TO IMPLEMENT"
.
.IP "1." 4
git\-project\-help
.
.IP "2." 4
git\-project\-config \-l|\-\-list
.
.IP "3." 4
git\-project\-init \-\-no\-checkout
.
.IP "4." 4
git\-project\-clone \-\-no\-checkout
.
.IP "5." 4
git\-project\-component \-\-list \-\-add \-\-delete
.
.IP "6." 4
git\-project\-component COMPONENT follow BRANCH alias to \-\-branch/\-\-follow
.
.IP "7." 4
git\-project\-component COMPONENT is REPO alias to \-\-repo/\-\-is
.
.IP "" 0
.
.SH "GENERAL IMPROVEMENTS"
.
.IP "1." 4
Improve the documentation about the commands to run to install ronn
.
.IP "2." 4
Create make target to generate complete site with links to all pages and assisted navigation such as headers/footers with links to TOC/index next/previous topic, etc\.
.
.IP "" 0
.
.SH "NOTES"
.
.SS "Components"
.
.SH "COPYRIGHT"
\(co DevConSoft, 2015
.
.P
\(co Zenterio AB, 2015
.
.SH "LICENCE"
\fBgit\-project\fR is released under the MIT License \fIhttp://opensource\.org/licenses/mit\-license\.html\fR\.
.
.SH "REPORTING BUGS"
TBD
.
.SH "SEE ALSO"
TBD
